"""Initial catalogue, evidence, and private account schema."""
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('aliases', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey('tracker.franchise', null=True, blank=True, on_delete=models.SET_NULL, related_name='works')),
                ('title', models.CharField(max_length=1000)),
                ('original_title', models.CharField(max_length=1000, blank=True)),
                ('aliases', models.JSONField(default=list)),
                ('creators', models.ManyToManyField('tracker.creator', blank=True, related_name='works')),
                ('kind', models.CharField(max_length=20, choices=[('show', 'TV series'), ('movie', 'Movie'), ('anime', 'Anime'), ('web_novel', 'Web novel'), ('light_novel', 'Light novel')])),
                ('summary', models.TextField(blank=True)),
                ('language', models.CharField(max_length=20, blank=True)),
                ('status', models.CharField(max_length=50, blank=True)),
                ('canonical_url', models.URLField(max_length=2000, blank=True)),
                ('image_url', models.URLField(max_length=2000, blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('curated_fields', models.JSONField(default=dict, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey('tracker.work', on_delete=models.CASCADE, related_name='identities')),
                ('provider', models.CharField(max_length=50)),
                ('namespace', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['provider', 'namespace', 'external_id'], name='unique_external_identity')],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey('tracker.work', on_delete=models.CASCADE, related_name='units')),
                ('provider', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=1000)),
                ('label', models.CharField(max_length=200, blank=True)),
                ('ordinal', models.IntegerField(default=0)),
                ('canonical_url', models.URLField(max_length=2000, blank=True)),
                ('published_at', models.DateTimeField(null=True, blank=True)),
                ('modified_at', models.DateTimeField(null=True, blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['work', 'provider', 'external_id'], name='unique_source_unit')],
                'ordering': ['ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey('tracker.work', on_delete=models.CASCADE, related_name='editions')),
                ('unit', models.ForeignKey('tracker.unit', null=True, blank=True, on_delete=models.SET_NULL)),
                ('provider', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, blank=True)),
                ('title', models.CharField(max_length=1000)),
                ('volume_label', models.CharField(max_length=200, blank=True)),
                ('publisher', models.CharField(max_length=300, blank=True)),
                ('imprint', models.CharField(max_length=300, blank=True)),
                ('format', models.CharField(max_length=50, default='print')),
                ('language', models.CharField(max_length=20, default='ja')),
                ('release_date', models.DateField(null=True, blank=True)),
                ('canonical_url', models.URLField(max_length=2000, blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['provider', 'product_id', 'format', 'language'], name='unique_source_edition')],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)),
                ('scope_key', models.CharField(max_length=100, default='shared')),
                ('provider', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=1000, blank=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('excerpt', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(null=True, blank=True)),
                ('observed_at', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['scope_key', 'url', 'content_hash'], name='unique_document_version')],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_work', models.ForeignKey('tracker.work', on_delete=models.CASCADE, related_name='outgoing_relationships')),
                ('to_work', models.ForeignKey('tracker.work', on_delete=models.CASCADE, related_name='incoming_relationships')),
                ('kind', models.CharField(max_length=30)),
                ('source', models.ForeignKey('tracker.sourcedocument', null=True, blank=True, on_delete=models.PROTECT)),
                ('verification', models.CharField(max_length=30, default='reported')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['from_work', 'to_work', 'kind'], name='unique_work_relationship')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)),
                ('scope_key', models.CharField(max_length=100, default='shared')),
                ('work', models.ForeignKey('tracker.work', on_delete=models.CASCADE, related_name='events')),
                ('unit', models.ForeignKey('tracker.unit', null=True, blank=True, on_delete=models.SET_NULL)),
                ('edition', models.ForeignKey('tracker.edition', null=True, blank=True, on_delete=models.SET_NULL)),
                ('provider', models.CharField(max_length=50)),
                ('external_key', models.CharField(max_length=500)),
                ('kind', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=1000)),
                ('summary', models.TextField(blank=True)),
                ('verification', models.CharField(max_length=30, default='reported')),
                ('lifecycle', models.CharField(max_length=30, default='scheduled')),
                ('precision', models.CharField(max_length=20, default='unknown')),
                ('date_label', models.CharField(max_length=200, blank=True)),
                ('scheduled_at', models.DateTimeField(null=True, blank=True)),
                ('window_start', models.DateField(null=True, blank=True)),
                ('window_end', models.DateField(null=True, blank=True)),
                ('source_timezone', models.CharField(max_length=50, blank=True)),
                ('region', models.CharField(max_length=10, blank=True)),
                ('platform', models.CharField(max_length=100, blank=True)),
                ('language', models.CharField(max_length=20, blank=True)),
                ('published_at', models.DateTimeField(null=True, blank=True)),
                ('observed_at', models.DateTimeField()),
                ('curated_fields', models.JSONField(default=dict, blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['scope_key', 'work', 'provider', 'external_key'], name='unique_source_event')],
                'indexes': [models.Index(fields=['window_start', 'kind'], name='tracker_event_date_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey('tracker.sourcedocument', on_delete=models.PROTECT, related_name='claims')),
                ('event', models.ForeignKey('tracker.event', null=True, blank=True, on_delete=models.CASCADE, related_name='claims')),
                ('work', models.ForeignKey('tracker.work', null=True, blank=True, on_delete=models.CASCADE)),
                ('payload', models.JSONField(default=dict)),
                ('locator', models.CharField(max_length=1000, blank=True)),
                ('original_text', models.TextField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['source', 'event'], name='unique_event_evidence')],
            },
        ),
        migrations.CreateModel(
            name='EventRevision',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey('tracker.event', on_delete=models.CASCADE, related_name='revisions')),
                ('actor', models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)),
                ('source', models.ForeignKey('tracker.sourcedocument', null=True, on_delete=models.PROTECT)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='follows')),
                ('work', models.ForeignKey('tracker.work', null=True, blank=True, on_delete=models.CASCADE)),
                ('franchise', models.ForeignKey('tracker.franchise', null=True, blank=True, on_delete=models.CASCADE)),
                ('include_related', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=20, default='planned')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('progress_kind', models.CharField(max_length=20, default='episode')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=Q(work__isnull=False, franchise__isnull=True) | Q(work__isnull=True, franchise__isnull=False), name='follow_one_target'), models.UniqueConstraint(fields=['owner', 'work'], name='unique_user_work_follow'), models.UniqueConstraint(fields=['owner', 'franchise'], name='unique_user_franchise_follow')],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AdapterState',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.OneToOneField('tracker.externalidentity', on_delete=models.CASCADE, related_name='adapter_state')),
                ('last_good_snapshot', models.JSONField(default=dict)),
                ('missing_counts', models.JSONField(default=dict)),
                ('last_checked_at', models.DateTimeField(null=True, blank=True)),
                ('last_success_at', models.DateTimeField(null=True, blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('diagnostics', models.JSONField(default=list)),
                ('lease_until', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)),
                ('identity', models.ForeignKey('tracker.externalidentity', null=True, blank=True, on_delete=models.CASCADE)),
                ('work', models.ForeignKey('tracker.work', null=True, blank=True, on_delete=models.CASCADE)),
                ('provider', models.CharField(max_length=50)),
                ('input', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=20, default='queued')),
                ('message', models.CharField(max_length=1000, blank=True)),
                ('finished_at', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)),
                ('provider', models.CharField(max_length=30, default='openai-compatible')),
                ('endpoint', models.URLField(max_length=2000)),
                ('model', models.CharField(max_length=200)),
                ('credential_ciphertext', models.TextField(blank=True)),
                ('max_input_chars', models.PositiveIntegerField(default=12000)),
                ('max_output_tokens', models.PositiveIntegerField(default=2000)),
                ('daily_requests', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)),
                ('date', models.DateField()),
                ('requests', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['owner', 'date'], name='unique_daily_model_usage')],
            },
        ),
        migrations.CreateModel(
            name='ReviewProposal',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)),
                ('work', models.ForeignKey('tracker.work', on_delete=models.CASCADE)),
                ('source', models.ForeignKey('tracker.sourcedocument', on_delete=models.PROTECT)),
                ('external_key', models.CharField(max_length=500)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=20, default='pending')),
                ('model', models.CharField(max_length=200, blank=True)),
                ('message', models.TextField(blank=True)),
                ('event', models.ForeignKey('tracker.event', null=True, blank=True, on_delete=models.SET_NULL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['owner', 'work', 'source', 'external_key'], name='unique_review_claim')],
            },
        ),
        migrations.CreateModel(
            name='FeedSubscription',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)),
                ('work', models.ForeignKey('tracker.work', on_delete=models.CASCADE)),
                ('url', models.URLField(max_length=2000)),
                ('source_kind', models.CharField(max_length=30, default='rss')),
                ('last_checked_at', models.DateTimeField(null=True, blank=True)),
                ('last_error', models.CharField(max_length=1000, blank=True)),
                ('seen_ids', models.JSONField(default=list)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['owner', 'work', 'url'], name='unique_user_feed')],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
