"""Generate client types directly from the API's Pydantic models; no Django startup needed."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "apps/backend"))
from tracker.schemas import CONTRACT_MODELS  # noqa: E402


def ts_type(schema):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "anyOf" in schema or "oneOf" in schema:
        return " | ".join(ts_type(value) for value in schema.get("anyOf", schema.get("oneOf")))
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        if properties:
            required = set(schema.get("required", []))
            return "{\n" + "\n".join(f"  {json.dumps(name)}{'' if name in required else '?'}: {ts_type(value)};" for name, value in properties.items()) + "\n}"
        additional = schema.get("additionalProperties", {})
        return f"Record<string, {ts_type(additional) if isinstance(additional, dict) else 'unknown'}>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def generate():
    definitions = {}
    for model in CONTRACT_MODELS:
        schema = model.model_json_schema()
        definitions.update(schema.pop("$defs", {}))
        definitions[model.__name__] = schema
    schema_file = ROOT / "packages/contracts/schema.json"
    output = ROOT / "apps/web/src/api/contracts.ts"
    schema_file.parent.mkdir(parents=True, exist_ok=True)
    output.parent.mkdir(parents=True, exist_ok=True)
    bundle = {"$schema": "https://json-schema.org/draft/2020-12/schema", "$defs": definitions}
    schema_file.write_text(json.dumps(bundle, ensure_ascii=False, indent=2) + "\n")
    output.write_text("// Generated by scripts/generate_contracts.py. Do not edit.\n\n" + "\n\n".join(f"export type {name} = {ts_type(schema)};" for name, schema in sorted(definitions.items())) + "\n")
    print(f"Generated {len(definitions)} API types")


if __name__ == "__main__":
    generate()
