<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { api, json } from '../api/client';
import type { FollowOut, ProgressIn } from '../api/contracts';
import { mediaLabel, openSearch, report, success } from '../composables/ui';
import PageHeading from '../components/PageHeading.vue';
const follows = ref<FollowOut[]>([]), loading = ref(true), query = ref(''), status = ref(''), editing = ref<FollowOut | null>(null), saving = ref(false);
const form = ref<ProgressIn>({ status: 'planned', progress: 0, include_related: false, progress_kind: 'episode' });
const statuses = [{ label: 'Planned', value: 'planned' }, { label: 'In progress', value: 'in_progress' }, { label: 'Completed', value: 'completed' }, { label: 'Paused', value: 'paused' }, { label: 'Dropped', value: 'dropped' }];
const visible = computed(() => follows.value.filter(row => (!status.value || row.status === status.value) && (row.work?.title || row.franchise_title || '').toLocaleLowerCase().includes(query.value.toLocaleLowerCase())));
async function load() { try { follows.value = await api<FollowOut[]>('/library'); } catch (err) { report(err); } finally { loading.value = false; } }
function edit(row: FollowOut) { editing.value = row; form.value = { status: row.status as ProgressIn['status'], progress: row.progress, include_related: row.include_related, progress_kind: row.progress_kind as ProgressIn['progress_kind'] }; }
async function save() { if (!editing.value) return; saving.value = true; try { await api(`/library/${editing.value.id}`, json(form.value, 'PATCH')); editing.value = null; await load(); success('Progress saved'); } catch (err) { report(err); } finally { saving.value = false; } }
async function unfollow() { if (!editing.value) return; saving.value = true; try { await api(`/library/${editing.value.id}`, { method: 'DELETE' }); editing.value = null; await load(); success('Story removed from your library'); } catch (err) { report(err); } finally { saving.value = false; } }
const changed = () => void load();
onMounted(() => { void load(); window.addEventListener('catalogue-updated', changed); });
onUnmounted(() => window.removeEventListener('catalogue-updated', changed));
</script>
<template>
  <q-page class="page"><PageHeading title="Your collection of stories" subtitle="What you’re watching, reading, and looking forward to."><q-btn unelevated color="primary" no-caps icon="add" label="Follow a story" @click="openSearch()" /></PageHeading>
    <div class="collection-toolbar"><q-input v-model="query" outlined dense placeholder="Find in your library" aria-label="Find in your library"><template #prepend><q-icon name="search" /></template></q-input><q-select v-model="status" :options="[{ label: 'All statuses', value: '' }, ...statuses]" emit-value map-options outlined dense label="Progress" /><span class="muted">{{ visible.length }} stories</span></div>
    <q-linear-progress v-if="loading" indeterminate color="primary" />
    <div v-else-if="!visible.length" class="empty-state"><span class="empty-symbol"><q-icon name="auto_stories" /></span><h2>{{ follows.length ? 'No stories match this view' : 'Make room for a new favourite' }}</h2><p>Search by title, author, URL, or a provider identifier.</p><q-btn unelevated color="primary" no-caps label="Find a story" @click="openSearch()" /></div>
    <div v-else class="library-grid"><article v-for="row in visible" :key="row.id" :class="['library-card', row.work?.kind || 'franchise']"><div class="library-art"><q-icon :name="row.work?.kind?.includes('novel') ? 'menu_book' : row.work?.kind === 'movie' ? 'movie' : 'auto_awesome'" /><span>{{ row.work ? mediaLabel(row.work.kind) : 'Franchise' }}</span><span v-if="row.work?.metadata.demo" class="demo-label">Demo story</span></div><div class="library-body"><router-link v-if="row.work" :to="`/works/${row.work.id}`" class="library-title">{{ row.work.title }}</router-link><h2 v-else>{{ row.franchise_title }}</h2><p class="library-author">{{ row.work?.creators.join(' · ') || 'Creator not yet available' }}</p><div class="library-progress"><span :class="['progress-badge', row.status]">{{ row.status.replace('_', ' ') }}</span><strong>{{ row.progress }} <small>{{ row.progress_kind }}{{ row.progress === 1 ? '' : 's' }}</small></strong></div><p v-if="row.include_related" class="related-note"><q-icon name="account_tree" /> Includes sequels and adaptations</p><q-btn flat no-caps icon="edit_note" label="Update progress" class="full-width" @click="edit(row)" /></div></article></div>
    <q-dialog :model-value="!!editing" @update:model-value="value => { if (!value) editing = null; }"><q-card class="small-dialog"><q-form @submit="save"><q-card-section><div class="eyebrow">YOUR PROGRESS</div><h2>{{ editing?.work?.title || editing?.franchise_title }}</h2><div class="form-stack"><q-select v-model="form.status" :options="statuses" emit-value map-options outlined label="Status" /><div class="two-fields"><q-input v-model.number="form.progress" type="number" min="0" max="1000000" outlined label="Completed" :rules="[value => Number.isInteger(Number(value)) && Number(value) >= 0 || 'Enter a whole number']" /><q-select v-model="form.progress_kind" :options="['episode', 'chapter', 'volume']" outlined label="Unit" /></div><q-checkbox v-model="form.include_related" label="Include sequels and adaptations" /><p class="muted">Your progress is visible only in your account.</p></div></q-card-section><q-card-actions><q-btn flat color="negative" no-caps label="Unfollow" :disable="saving" @click="unfollow" /><q-space /><q-btn flat no-caps label="Cancel" v-close-popup /><q-btn unelevated color="primary" no-caps label="Save progress" type="submit" :loading="saving" /></q-card-actions></q-form></q-card></q-dialog>
  </q-page>
</template>
