<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { signIn } from '../api/client';

const username = ref(''); const password = ref(''); const loading = ref(false); const error = ref('');
const router = useRouter();
async function login() { error.value = ''; loading.value = true; try { await signIn(username.value, password.value); await router.replace('/'); } catch (e) { error.value = e instanceof Error ? e.message : 'Could not sign in'; } finally { loading.value = false; } }
</script>
<template><main class="login-page"><div class="login-story"><div class="brand"><span class="brand-mark"><q-icon name="all_inclusive" /></span><span>Release<span class="brand-light">Holic</span></span></div><div class="login-copy"><div class="eyebrow">FOR THE STORIES YOU LOVE</div><h1>The next chapter.<br>Always in sight.</h1><p>From the first announcement to the final episode. Your shows, anime, films, and novels—one thoughtful timeline.</p><div class="login-illustration" aria-hidden="true"><span class="illustration-spine" /><div class="illustration-card"><span class="illustration-dot purple" /><small>THE FIRST WORD</small><strong>A new season is announced</strong><span>Announcement · Reported</span></div><div class="illustration-card offset"><span class="illustration-dot peach" /><small>A LITTLE CLOSER</small><strong>The trailer arrives</strong><span>PV · Official channel</span></div><div class="illustration-card"><span class="illustration-dot green" /><small>THE NEXT CHAPTER</small><strong>Premiere day</strong><span>Release · Your region</span></div></div></div><small class="login-tagline">An evidence-backed home for your watchlist.</small></div><section class="login-form"><div class="eyebrow">WELCOME BACK</div><h2>Follow the story.</h2><p class="muted">Sign in to your Release-Holic server.</p><q-form @submit="login"><q-input v-model="username" outlined label="Username" autocomplete="username" :rules="[v => !!v || 'Enter your username']" /><q-input v-model="password" outlined type="password" label="Password" autocomplete="current-password" :rules="[v => !!v || 'Enter your password']" /><p v-if="error" role="alert" class="error-text">{{ error }}</p><q-btn type="submit" color="primary" unelevated label="Sign in" no-caps :loading="loading" class="full-width" size="lg" /></q-form><div class="login-help"><q-icon name="lock_outline" /> Your progress and model credentials belong to your account.</div><p class="muted login-account-help">Accounts are created by your server administrator.</p></section></main></template>
