<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import { api, json, trackRun } from '../api/client';
import type { FeedIn, FeedOut, RunOut, SourcesOut, WorkOut } from '../api/contracts';
import { report, success, timestampLabel } from '../composables/ui';
import PageHeading from '../components/PageHeading.vue';
const sources = ref<SourcesOut | null>(null), feeds = ref<FeedOut[]>([]), works = ref<WorkOut[]>([]), runs = ref<RunOut[]>([]), loading = ref(true);
const addOpen = ref(false), articleOpen = ref(false), saving = ref(false), workId = ref(''), url = ref(''), sourceKind = ref<FeedIn['source_kind']>('rss'), useModel = ref(false);
const sourceOptions = [{ label: 'RSS / Atom feed', value: 'rss' }, { label: 'Official YouTube channel feed', value: 'youtube' }, { label: 'Apple TV press room', value: 'apple' }, { label: 'Netflix newsroom', value: 'netflix' }, { label: 'Disney press room', value: 'disney' }];
async function load() { try { const [data, subscriptions, catalogue, jobs] = await Promise.all([api<SourcesOut>('/sources'), api<FeedOut[]>('/feeds'), api<WorkOut[]>('/works'), api<RunOut[]>('/runs')]); sources.value = data; feeds.value = subscriptions; works.value = catalogue; runs.value = jobs; } catch (err) { report(err); } finally { loading.value = false; } }
function start(mode: 'feed' | 'article') { workId.value = ''; url.value = ''; sourceKind.value = 'rss'; useModel.value = false; addOpen.value = mode === 'feed'; articleOpen.value = mode === 'article'; }
async function submit() {
  saving.value = true;
  try { if (articleOpen.value) { const run = await api<RunOut>('/articles', json({ work_id: workId.value, url: url.value, use_model: useModel.value })); trackRun(run); success('Source queued for review'); } else { await api('/feeds', json({ work_id: workId.value, url: url.value, source_kind: sourceKind.value })); success('Source monitor added'); } articleOpen.value = false; addOpen.value = false; await load(); }
  catch (err) { report(err); }
  finally { saving.value = false; }
}
async function remove(feed: FeedOut) { try { await api(`/feeds/${feed.id}`, { method: 'DELETE' }); await load(); } catch (err) { report(err); } }
const changed = () => void load();
onMounted(() => { void load(); window.addEventListener('catalogue-updated', changed); });
onUnmounted(() => window.removeEventListener('catalogue-updated', changed));
</script>
<template>
  <q-page class="page"><PageHeading title="The stories behind the stories" subtitle="Connected catalogues, official sources, and collection health."><q-btn outline no-caps icon="add_link" label="Submit an article" @click="start('article')" /><q-btn unelevated color="primary" no-caps icon="rss_feed" label="Add monitor" @click="start('feed')" /></PageHeading><q-linear-progress v-if="loading" indeterminate />
    <div class="source-grid"><article v-for="adapter in sources?.adapters" :key="adapter.provider" class="adapter-card"><div><span class="adapter-icon"><q-icon :name="adapter.provider === 'kakuyomu' || ['kadokawa', 'gagaga', 'ndl'].includes(adapter.provider) ? 'menu_book' : adapter.provider === 'bangumi' ? 'auto_awesome' : 'live_tv'" /></span><span :class="['status-dot', adapter.status === 'ready' ? 'ready' : 'attention']" /> <small>{{ adapter.status.replaceAll('_', ' ') }}</small></div><h2>{{ adapter.provider }}</h2><p>{{ adapter.policy }}</p></article></div>
    <section class="content-section"><div class="section-heading"><div><div class="eyebrow">ALWAYS LISTENING</div><h2>Your source monitors</h2></div><q-btn flat no-caps icon="sync" label="Refresh status" @click="load" /></div><p v-if="!feeds.length" class="inline-empty">Add an official press page, channel feed, or RSS source for a followed story.</p><div v-else class="table-scroll"><table class="data-table"><thead><tr><th>Story / source</th><th>Last checked</th><th>Health</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody><tr v-for="feed in feeds" :key="feed.id"><td><router-link :to="`/works/${feed.work_id}`">{{ works.find(work => work.id === feed.work_id)?.title || 'Story' }}</router-link><small><a :href="feed.url" target="_blank" rel="noopener noreferrer">{{ feed.source_kind }} · {{ feed.url }}</a></small></td><td>{{ timestampLabel(feed.last_checked_at) }}</td><td><span v-if="feed.last_error" class="error-text">{{ feed.last_error }}</span><span v-else class="healthy-text">{{ feed.last_checked_at ? 'Collecting normally' : 'Waiting for worker' }}</span></td><td><q-btn flat round size="sm" icon="delete_outline" :aria-label="`Remove ${feed.source_kind} monitor`" @click="remove(feed)" /></td></tr></tbody></table></div></section>
    <section class="content-section"><div class="section-heading"><div><div class="eyebrow">COLLECTION HEALTH</div><h2>Catalogue adapters</h2></div></div><p v-if="!sources?.states.length" class="inline-empty">Adapter health appears after a story has been imported.</p><div v-else class="health-list"><article v-for="state in sources.states" :key="state.id" class="health-row"><span :class="['status-dot', state.last_error ? 'attention' : 'ready']" /><div><router-link :to="`/works/${state.work_id}`">{{ state.work_title }}</router-link><small>{{ state.provider }} · Last success {{ timestampLabel(state.last_success_at) }}</small><p v-if="state.last_error" class="error-text">{{ state.last_error }}</p><p v-for="diagnostic in state.diagnostics" :key="diagnostic" class="muted">{{ diagnostic }}</p></div><q-icon :name="state.last_error ? 'error_outline' : 'check_circle_outline'" :color="state.last_error ? 'warning' : 'positive'" /></article></div></section>
    <section class="content-section"><div class="section-heading"><div><div class="eyebrow">RECENT ACTIVITY</div><h2>Ingestion jobs</h2></div></div><p v-if="!runs.length" class="inline-empty">Imports and article submissions appear here.</p><div v-else class="table-scroll"><table class="data-table"><thead><tr><th>Source</th><th>Status</th><th>Started</th><th>Result</th></tr></thead><tbody><tr v-for="run in runs" :key="run.id"><td>{{ run.provider }}</td><td><span :class="['job-badge', run.status]">{{ run.status }}</span></td><td>{{ timestampLabel(run.created_at) }}</td><td>{{ run.message || 'Awaiting collection' }}</td></tr></tbody></table></div></section>
    <q-dialog :model-value="addOpen || articleOpen" @update:model-value="value => { if (!value) { addOpen = false; articleOpen = false; } }"><q-card class="small-dialog"><q-form @submit="submit"><q-card-section><h2>{{ articleOpen ? 'Submit a source for review' : 'Monitor a source' }}</h2><p class="muted">Tie each source to a specific story to keep its claims identifiable.</p><div class="form-stack"><q-select v-model="workId" :options="works.map(work => ({ label: work.title, value: work.id }))" emit-value map-options outlined label="Story" :rules="[value => !!value || 'Choose a story']" /><q-select v-if="!articleOpen" v-model="sourceKind" :options="sourceOptions" emit-value map-options outlined label="Source type" /><q-input v-if="articleOpen || sourceKind === 'rss' || sourceKind === 'youtube'" v-model="url" type="url" outlined label="Source URL" :rules="[value => !!value || 'Enter a URL']" :hint="sourceKind === 'youtube' && !articleOpen ? 'https://www.youtube.com/feeds/videos.xml?channel_id=…' : 'The host must be enabled by your server administrator.'" /><p v-else class="muted">The official press page is monitored for this story’s title and aliases.</p><q-checkbox v-if="articleOpen" v-model="useModel" label="Extract claims using my model" /><p v-if="articleOpen" class="muted">Extracted claims enter your review queue. Configure your model in Settings.</p></div></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancel" v-close-popup /><q-btn type="submit" unelevated color="primary" no-caps :label="articleOpen ? 'Queue source' : 'Add monitor'" :loading="saving" /></q-card-actions></q-form></q-card></q-dialog>
  </q-page>
</template>
