<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { api, json, queryString, trackRun, user } from '../api/client';
import type { FollowOut, FranchiseOut, RunOut, TimelineOut, WorkDetailOut } from '../api/contracts';
import { displayTimezone, mediaLabel, report, success } from '../composables/ui';
import EventCard from '../components/EventCard.vue';
const route = useRoute(), detail = ref<WorkDetailOut | null>(null), timeline = ref<TimelineOut | null>(null), ownFollow = ref<FollowOut | null>(null);
const loading = ref(true), error = ref(''), refreshing = ref(false), includeRelated = ref(false), tab = ref('timeline');
const correctionOpen = ref(false), correctionTitle = ref(''), correctionAliases = ref(''), franchiseId = ref('');
const franchises = ref<FranchiseOut[]>([]);
const work = computed(() => detail.value?.work), units = computed(() => detail.value?.units.filter(unit => unit.active) || []);
let generation = 0;
async function load() {
  const current = ++generation, id = String(route.params.id); error.value = '';
  try { const [data, events, library] = await Promise.all([api<WorkDetailOut>(`/works/${id}`), api<TimelineOut>('/timeline?' + queryString({ work_id: id, library_only: false, display_timezone: displayTimezone(), limit: 100 })), api<FollowOut[]>('/library')]); if (current !== generation) return; detail.value = data; timeline.value = events; ownFollow.value = library.find(row => row.work?.id === id) || null; includeRelated.value = ownFollow.value?.include_related || false; }
  catch (err) { if (current === generation) error.value = err instanceof Error ? err.message : 'Could not load this story.'; }
  finally { if (current === generation) loading.value = false; }
}
async function follow() { if (!work.value) return; try { ownFollow.value = await api<FollowOut>('/library', json({ work_id: work.value.id, include_related: includeRelated.value })); success('Story added to your library'); } catch (err) { report(err); } }
async function followFranchise() { if (!work.value?.franchise_id) return; try { await api('/library', json({ franchise_id: work.value.franchise_id, include_related: true })); success('Franchise followed, including related works'); } catch (err) { report(err); } }
async function refresh() { if (!work.value) return; refreshing.value = true; try { const runs = await api<RunOut[]>(`/works/${work.value.id}/refresh`, json({})); runs.forEach(trackRun); success(runs.length ? 'Metadata refresh queued' : 'This record has no automatic adapter. Add a source in Sources.'); } catch (err) { report(err); } finally { refreshing.value = false; } }
async function editMetadata() { if (!work.value) return; correctionTitle.value = work.value.title; correctionAliases.value = work.value.aliases.join('\n'); franchiseId.value = work.value.franchise_id || ''; correctionOpen.value = true; try { franchises.value = await api<FranchiseOut[]>('/franchises'); } catch (err) { report(err); } }
async function correct() { if (!work.value) return; try { await api(`/works/${work.value.id}`, json({ title: correctionTitle.value, aliases: correctionAliases.value.split('\n').map(item => item.trim()).filter(Boolean), franchise_id: franchiseId.value || null }, 'PATCH')); correctionOpen.value = false; await load(); success('Catalogue correction saved'); } catch (err) { report(err); } }
function relatedTarget(fromId: string, toId: string) { return work.value?.id === fromId ? toId : fromId; }
const changed = () => void load();
watch(() => route.params.id, () => { loading.value = true; void load(); });
onMounted(() => { void load(); window.addEventListener('catalogue-updated', changed); });
onUnmounted(() => { generation++; window.removeEventListener('catalogue-updated', changed); });
</script>
<template>
  <q-page class="page"><router-link to="/library" class="back-link"><q-icon name="arrow_back" /> Back to library</router-link><q-linear-progress v-if="loading" indeterminate /><div v-if="error" role="alert" class="error-panel"><p>{{ error }}</p><q-btn outline no-caps label="Try again" @click="load" /></div>
    <template v-if="work"><div v-if="work.metadata.demo" class="demo-banner"><q-icon name="science" /> This fictional story is demonstration data.</div><div :class="['work-hero', work.kind]"><div class="work-art"><q-icon :name="work.kind.includes('novel') ? 'menu_book' : work.kind === 'movie' ? 'movie' : 'auto_awesome'" /></div><div class="work-hero-content"><div class="eyebrow">{{ mediaLabel(work.kind) }} <span v-if="work.language">· {{ work.language }}</span></div><h1>{{ work.title }}</h1><p v-if="work.original_title && work.original_title !== work.title" class="original-title">{{ work.original_title }}</p><p class="work-creators">{{ work.creators.join(' · ') }}</p><div class="work-badges"><q-badge outline>{{ work.status.replaceAll('_', ' ') || 'Status unknown' }}</q-badge><q-badge v-if="work.franchise_title" outline>{{ work.franchise_title }}</q-badge><q-badge outline>{{ work.unit_count }} indexed units</q-badge></div><p class="work-summary">{{ work.summary || 'Metadata will appear after this source is collected.' }}</p><div class="work-actions"><template v-if="!ownFollow"><q-btn unelevated color="primary" no-caps icon="add" label="Follow story" @click="follow" /><q-checkbox v-model="includeRelated" label="Include sequels & adaptations" /></template><q-btn v-else outline color="primary" no-caps icon="check" label="In your library" to="/library" /><q-btn flat no-caps icon="sync" label="Refresh sources" :loading="refreshing" @click="refresh" /><q-btn v-if="work.canonical_url" flat no-caps icon="open_in_new" label="Original source" :href="work.canonical_url" target="_blank" rel="noopener noreferrer" /><q-btn v-if="user?.is_staff" flat no-caps icon="edit" label="Correct metadata" @click="editMetadata" /></div></div></div>
      <div class="work-details-grid"><section><q-tabs v-model="tab" no-caps align="left" active-color="primary" indicator-color="primary" class="detail-tabs"><q-tab name="timeline" label="Timeline" /><q-tab name="units" :label="`Episodes / chapters (${units.length})`" /><q-tab name="editions" :label="`Editions (${detail?.editions.length || 0})`" /></q-tabs><div v-if="tab === 'timeline'" class="work-event-list"><EventCard v-for="event in timeline?.events" :key="event.id" :event="event" /><p v-if="!timeline?.events.length" class="inline-empty">No events collected yet. Check Sources for the ingestion status.</p><p v-if="timeline && timeline.total > timeline.events.length" class="muted">Showing the first {{ timeline.events.length }} events. The main timeline supports the full history.</p></div><q-list v-else-if="tab === 'units'" separator class="unit-list"><q-item v-for="unit in units" :key="unit.id" :href="unit.canonical_url || undefined" target="_blank" rel="noopener noreferrer"><q-item-section side><span class="unit-number">{{ unit.label || unit.ordinal }}</span></q-item-section><q-item-section><q-item-label>{{ unit.title }}</q-item-label><q-item-label caption>{{ unit.provider }} · {{ unit.kind }}</q-item-label></q-item-section><q-item-section side><q-icon name="open_in_new" size="16px" /></q-item-section></q-item><p v-if="!units.length" class="inline-empty">No indexed episodes or chapters.</p></q-list><div v-else class="edition-list"><article v-for="edition in detail?.editions" :key="edition.id" class="edition-card"><q-icon name="menu_book" /><div><h3>{{ edition.title }} <span>{{ edition.volume_label }}</span></h3><p>{{ edition.publisher }} · {{ edition.format }} · {{ edition.language }}</p><p>ISBN {{ edition.isbn || 'not yet available' }}<span v-if="edition.release_date"> · {{ edition.release_date }}</span></p><a v-if="edition.canonical_url" :href="edition.canonical_url" target="_blank" rel="noopener noreferrer">Publisher / bibliographic record <q-icon name="open_in_new" /></a></div></article><p v-if="!detail?.editions.length" class="inline-empty">No editions collected yet.</p></div></section>
      <aside class="work-sidebar"><section class="info-panel"><h2>Connected stories</h2><router-link v-for="relationship in detail?.relationships" :key="relationship.id" :to="`/works/${relatedTarget(relationship.from_work_id, relationship.to_work_id)}`" class="relationship-link"><small>{{ relationship.kind.replaceAll('_', ' ') }} · {{ relationship.verification }}</small><strong>{{ work.id === relationship.from_work_id ? relationship.to_title : relationship.from_title }}</strong><q-icon name="arrow_outward" /></router-link><p v-if="!detail?.relationships.length" class="muted">Related works appear when their identities are resolved.</p><q-btn v-if="work.franchise_id" flat color="primary" no-caps label="Follow whole franchise" icon="account_tree" @click="followFranchise" /></section><section class="info-panel"><h2>Source identities</h2><div v-for="identity in work.identities" :key="identity.id" class="identity-row"><strong>{{ identity.provider }}</strong><code>{{ identity.namespace }}:{{ identity.external_id }}</code></div><p class="muted">Each source keeps its own numbering and edition identity.</p></section></aside></div>
    </template>
    <q-dialog v-model="correctionOpen"><q-card class="small-dialog"><q-form @submit="correct"><q-card-section><h2>Correct catalogue metadata</h2><div class="form-stack"><q-input v-model="correctionTitle" outlined label="Display title" :rules="[value => !!value || 'Enter a title']" /><q-input v-model="correctionAliases" outlined type="textarea" label="Aliases (one per line)" /><q-select v-model="franchiseId" :options="[{ label: 'No franchise', value: '' }, ...franchises.map(item => ({ label: item.title, value: item.id }))]" emit-value map-options outlined label="Franchise" /><p class="muted">Create franchises and edit relationships in the Django administration interface.</p></div></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancel" v-close-popup /><q-btn type="submit" unelevated color="primary" no-caps label="Save correction" /></q-card-actions></q-form></q-card></q-dialog>
  </q-page>
</template>
