// Generated by scripts/generate_contracts.py. Do not edit.

export type ArticleIn = {
  "work_id": string;
  "url": string;
  "use_model"?: boolean;
};

export type Candidate = {
  "provider": string;
  "namespace": string;
  "external_id": string;
  "title": string;
  "kind": string;
  "creators"?: Array<string>;
  "year"?: string;
  "url"?: string;
  "existing_work_id"?: string | null;
};

export type EditionOut = {
  "id": string;
  "title": string;
  "isbn": string;
  "volume_label": string;
  "publisher": string;
  "imprint": string;
  "format": string;
  "language": string;
  "release_date": string | null;
  "canonical_url": string;
};

export type EventDetailOut = {
  "event": EventOut;
  "evidence": Array<EvidenceOut>;
  "revisions": Array<RevisionOut>;
};

export type EventOut = {
  "id": string;
  "work_id": string;
  "work_title": string;
  "work_kind": string;
  "franchise_id": string | null;
  "kind": string;
  "title": string;
  "summary": string;
  "verification": string;
  "lifecycle": string;
  "precision": string;
  "date_label": string;
  "scheduled_at": string | null;
  "window_start": string | null;
  "window_end": string | null;
  "source_timezone": string;
  "region": string;
  "platform": string;
  "language": string;
  "published_at": string | null;
  "observed_at": string;
  "provider": string;
  "evidence_count": number;
  "personal": boolean;
};

export type EvidenceOut = {
  "id": string;
  "url": string;
  "provider": string;
  "title": string;
  "locator": string;
  "original_text": string;
  "published_at": string | null;
  "observed_at": string;
};

export type FeedIn = {
  "work_id": string;
  "url": string;
  "source_kind"?: "rss" | "youtube" | "apple" | "netflix" | "disney";
};

export type FeedOut = {
  "work_id": string;
  "url": string;
  "source_kind"?: "rss" | "youtube" | "apple" | "netflix" | "disney";
  "id": string;
  "last_checked_at": string | null;
  "last_error": string;
};

export type FilterIn = {
  "name": string;
  "filters": Record<string, unknown>;
};

export type FilterOut = {
  "name": string;
  "filters": Record<string, unknown>;
  "id": string;
};

export type FollowIn = {
  "work_id"?: string | null;
  "franchise_id"?: string | null;
  "include_related"?: boolean;
};

export type FollowOut = {
  "id": string;
  "work": WorkOut | null;
  "franchise_id": string | null;
  "franchise_title": string | null;
  "include_related": boolean;
  "status": string;
  "progress": number;
  "progress_kind": string;
};

export type FranchiseOut = {
  "id": string;
  "title": string;
};

export type IdentityOut = {
  "provider": string;
  "namespace": string;
  "external_id": string;
  "id": string;
};

export type ImportIn = {
  "provider": string;
  "namespace": string;
  "external_id": string;
  "include_related"?: boolean;
};

export type LoginIn = {
  "username": string;
  "password": string;
};

export type LoginOut = {
  "token": string;
  "user": UserOut;
};

export type ModelIn = {
  "provider": "openai-compatible" | "openai" | "anthropic" | "google" | "ollama";
  "endpoint": string;
  "model": string;
  "credential"?: string | null;
  "max_input_chars"?: number;
  "max_output_tokens"?: number;
  "daily_requests"?: number;
};

export type ModelOut = {
  "provider": string;
  "endpoint": string;
  "model": string;
  "has_credential": boolean;
  "max_input_chars": number;
  "max_output_tokens": number;
  "daily_requests": number;
};

export type Precision = "instant" | "day" | "month" | "season" | "year" | "unknown";

export type ProgressIn = {
  "status": "planned" | "in_progress" | "completed" | "paused" | "dropped";
  "progress": number;
  "include_related": boolean;
  "progress_kind": "episode" | "chapter" | "volume";
};

export type RelationshipOut = {
  "id": string;
  "kind": string;
  "from_work_id": string;
  "to_work_id": string;
  "from_title": string;
  "to_title": string;
  "verification": string;
};

export type ReleaseTime = {
  "precision"?: Precision;
  "start"?: string | null;
  "end"?: string | null;
  "timestamp"?: string | null;
  "label"?: string;
  "timezone"?: string;
};

export type ReviewIn = {
  "action": "approve" | "reject";
  "payload"?: SourceEvent | null;
};

export type ReviewOut = {
  "id": string;
  "work_id": string;
  "work_title": string;
  "source_url": string;
  "excerpt": string;
  "payload": SourceEvent;
  "model": string;
  "status": string;
  "message": string;
  "created_at": string;
};

export type RevisionOut = {
  "id": string;
  "before": Record<string, unknown>;
  "after": Record<string, unknown>;
  "reason": string;
  "created_at": string;
};

export type RunOut = {
  "id": string;
  "work_id": string | null;
  "provider": string;
  "status": string;
  "message": string;
  "created_at": string;
  "finished_at": string | null;
};

export type SearchOut = {
  "candidates": Array<Candidate>;
  "errors": Array<string>;
};

export type SourceEvent = {
  "external_key": string;
  "kind": "announcement" | "release" | "episode_release" | "chapter_release" | "volume_release" | "availability" | "pv" | "rumour" | "sequel" | "adaptation" | "delay" | "cancellation" | "metadata_change";
  "title": string;
  "summary"?: string;
  "release"?: ReleaseTime;
  "verification"?: "confirmed" | "reported" | "unverified" | "contradicted" | "retracted";
  "lifecycle"?: "announced" | "scheduled" | "released" | "delayed" | "cancelled";
  "region"?: string;
  "platform"?: string;
  "language"?: string;
  "url": string;
  "locator"?: string;
  "original_text"?: string;
  "published_at"?: string | null;
  "unit_id"?: string | null;
  "product_id"?: string | null;
};

export type SourceOut = {
  "provider": string;
  "status": string;
  "policy": string;
};

export type SourceStateOut = {
  "id": string;
  "work_id": string;
  "work_title": string;
  "provider": string;
  "last_checked_at": string | null;
  "last_success_at": string | null;
  "last_error": string;
  "diagnostics": Array<string>;
};

export type SourcesOut = {
  "adapters": Array<SourceOut>;
  "states": Array<SourceStateOut>;
};

export type StatsOut = {
  "followed": number;
  "upcoming": number;
  "needs_review": number;
  "stale_sources": number;
};

export type StatusOut = {
  "ok": boolean;
  "message"?: string;
};

export type TimelineOut = {
  "events": Array<EventOut>;
  "total": number;
  "tba_count": number;
  "offset": number;
  "limit": number;
};

export type UnitOut = {
  "id": string;
  "provider": string;
  "external_id": string;
  "kind": string;
  "title": string;
  "label": string;
  "ordinal": number;
  "canonical_url": string;
  "active": boolean;
};

export type UserOut = {
  "id": number;
  "username": string;
  "is_staff": boolean;
};

export type WorkCorrectionIn = {
  "title": string;
  "aliases": Array<string>;
  "franchise_id"?: string | null;
};

export type WorkDetailOut = {
  "work": WorkOut;
  "units": Array<UnitOut>;
  "editions": Array<EditionOut>;
  "relationships": Array<RelationshipOut>;
};

export type WorkOut = {
  "id": string;
  "title": string;
  "original_title": string;
  "aliases": Array<string>;
  "kind": string;
  "creators": Array<string>;
  "summary": string;
  "language": string;
  "status": string;
  "canonical_url": string;
  "image_url": string;
  "franchise_id": string | null;
  "franchise_title": string | null;
  "identities": Array<IdentityOut>;
  "unit_count": number;
  "metadata": Record<string, unknown>;
};
